// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace MinimalApiRecordTests.Data.Compiled
{
    public partial class DataContextModel
    {
        partial void Initialize()
        {
            var userData = UserDataEntityType.Create(this);

            UserDataEntityType.CreateAnnotations(userData);

            AddAnnotation("ProductVersion", "6.0.8");
        }
    }
}
