// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace MinimalApiRecordTests.Data.Compiled
{
    [DbContext(typeof(DataContext))]
    public partial class DataContextModel : RuntimeModel
    {
        static DataContextModel()
        {
            var model = new DataContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static DataContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
